### ISSUE TITLE
AttributeError: 'Ui_MainWindow' object has no attribute 'DATA__PATCH_SIZE__TEST__INPUT'

### ISSUE THREAD

**Issue by jichen12** [BiaPyX/BiaPy#122]
Hi, 

I've trained a Unet model for instance segmentation, and I wanted to use and test that model (inference). I loaded my pretrained BiaPy model, disabled `perform training`, typed my raw image folder path and disabled `test labels`. When I clicked on `create configuration`, I have: 

```
Unexpected error. Please contact BiaPy developers with the following error: 
Traceback (most recent call last):
  File "main.py", line 232, in <lambda>
  File "ui_utils.py", line 468, in change_page
  File "ui_utils.py", line 2713, in create_yaml_file
AttributeError: 'Ui_MainWindow' object has no attribute 'DATA__PATCH_SIZE__TEST__INPUT'
```

I don't think it's because the patch size is over my GPU because I used the same size for training.
Because I cannot create a new config file, I also tried to manually modify it without GUI and loaded it in GUI again, but I still have the same error. 

yaml file: 
```
AUGMENTOR:
  AFFINE_MODE: reflect
  BRIGHTNESS: true
  BRIGHTNESS_FACTOR: (-0.1, 0.1)
  CONTRAST: true
  CONTRAST_FACTOR: (-0.1, 0.1)
  ELASTIC: true
  ENABLE: true
  HFLIP: true
  RANDOM_ROT: true
  RANDOM_ROT_RANGE: (-180, 180)
  VFLIP: true
  ZFLIP: true
  ZOOM: true
  ZOOM_RANGE: (0.9, 1.1)
DATA:
  EXTRACT_RANDOM_PATCH: false
  PATCH_SIZE: (40,256,256,1)
  REFLECT_TO_COMPLETE_SHAPE: true
  TEST:
    ARGMAX_TO_OUTPUT: true
    GT_PATH: gt
    IN_MEMORY: true
    LOAD_GT: false
    OVERLAP: (0,0,0)
    PADDING: (5,16,16)
    PATH: D:\cell_tracking\normal\all_registered_rigid
    RESOLUTION: (1,1,1)
  TRAIN:
    GT_PATH: D:\cell_tracking\BiaPy\training\label
    IN_MEMORY: true
    OVERLAP: (0,0,0)
    PADDING: (0,0,0)
    PATH: D:\cell_tracking\BiaPy\training\raw
  VAL:
    FROM_TRAIN: true
    IN_MEMORY: true
    RANDOM: true
    RESOLUTION: (1,1,1)
    SPLIT_TRAIN: 0.1
LOSS:
  CLASS_REBALANCE: true
  TYPE: CE
MODEL:
  ARCHITECTURE: unet
  DROPOUT_VALUES:
  - 0.0
  - 0.0
  - 0.0
  FEATURE_MAPS:
  - 32
  - 64
  - 128
  N_CLASSES: 2
  Z_DOWN:
  - 0
  - 0
  - 0
  - 0
PROBLEM:
  INSTANCE_SEG:
    DATA_CHANNELS: BCM
    DATA_CHANNEL_WEIGHTS: (1,1)
    DATA_MW_TH_TYPE: auto
  NDIM: 3D
  TYPE: INSTANCE_SEG
SYSTEM:
  NUM_CPUS: -1
  NUM_WORKERS: 2
  SEED: 0
TEST:
  ENABLE: true
  MATCHING_STATS: true
  MATCHING_STATS_THS:
  - 0.3
  - 0.5
  - 0.75
  VERBOSE: true
TRAIN:
  BATCH_SIZE: 1
  ENABLE: false
  EPOCHS: 200
  LR: 0.0001
  OPTIMIZER: ADAMW
  OPT_BETAS: (0.9, 0.999)
  PATIENCE: 100
  W_DECAY: 0.02
```

Thank you so much for your help!
